apiVersion: v1
kind: Service
metadata:
  name: identity-backend
  namespace: identity
spec:
  type: ClusterIP
  selector:
    app: identity-backend
  ports:
    - port: 8000
      targetPort: 8000
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: identity-web
  namespace: identity
spec:
  type: ClusterIP
  selector:
    app: identity-web
  ports:
    - port: 80
      targetPort: 80
      name: http
