apiVersion: v1
kind: Service
metadata:
  name: workspace-mongodb
  namespace: workspace
spec:
  type: ClusterIP
  selector:
    app: workspace-mongodb
  ports:
    - port: 27017
      targetPort: 27017
      name: mongodb
