apiVersion: v1
kind: Service
metadata:
  name: identity-redis
  namespace: identity
spec:
  type: ClusterIP
  selector:
    app: identity-redis
  ports:
    - port: 6379
      targetPort: 6379
      name: redis
