apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - workspace-backend-deployment.yaml
  - workspace-backend-service.yaml
  - workspace-backend-hpa.yaml
  - workspace-web-deployment.yaml
  - workspace-web-service.yaml
  - ingress.yaml
