apiVersion: v1
kind: Service
metadata:
  name: workspace-backend
  namespace: workspace
spec:
  type: ClusterIP
  selector:
    app: workspace-backend
  ports:
    - port: 8001
      targetPort: 8001
      name: http
